name: Rest Assured Automation Tests

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Check Java version
        run: java -version

      - name: Check Maven version
        run: mvn -version

      - name: Run Rest Assured tests
        run: mvn clean test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            target/surefire-reports/
            test-output/